### ISSUE TITLE
Add download word to download buttons for large screens.

### ISSUE THREAD

**Issue by tmathews** [monstercat/deon#100]
Should only be applied to screens with a minimum resolution of 1080p.

**Comment by juanferreras** [comment]
This is for the buttons on the header of the release page? May we add in the words for all the buttons? So (play icon) PLAY - (download icon) DOWNLOAD - (copyright icon) LICENSE, etc. If not all, which ones should we display the name, only play and download?

**Comment by tmathews** [comment]
This would be in the track rows again. Might be good to do in the header of the release page too.
