### ISSUE TITLE
No cancellation button for Gold subscription on Services page

### ISSUE THREAD

**Issue by Vindexus** [monstercat/deon#105]
![Screenshot](https://puu.sh/tcgyK/8040eb3318.png)

UID: 564a09eddaa19afd5544d4dd

**Comment by Vindexus** [comment]
Also in the db the subscriptionActive field is `false`

**Comment by lostlevels** [comment]
@tmathews @Vindexus What do we want the text to say if they have days remaining on a cancelled subscription? "You have gold that will expire on ..." ?

**Comment by Vindexus** [comment]
That'd be good I guess.

The issue was that his subscription wasn't actually cancelled in PayPal.

**Comment by lostlevels** [comment]
The user had a "skipped" / soft failed payment in paypal where we mark the subscription inactive in the backend, but paypal doesnt have option to cancel on skipped payments (only failed payments). When the next payment was received, subscription wasn't marked as active on backend.
