### ISSUE TITLE
Better modals.

### ISSUE THREAD

**Issue by tmathews** [monstercat/deon#108]
We need to design better modals. The current ones below are an eye sore.

![53bb54b9888df6c710a282d6c6fd3afe](https://cloud.githubusercontent.com/assets/522209/21728710/8727143e-d3fc-11e6-8da9-4264c2a8f506.png)
![062a6941c9f827d71f5b3d36f1047cab](https://cloud.githubusercontent.com/assets/522209/21728711/873e2fa2-d3fc-11e6-8966-255f48202b39.png)

**Comment by juanferreras** [comment]
We should also build this escalable enough to get rid of all the `alert()` in replacement of the new good looking modals or toasties depending if we need user action or not.

**Comment by tmathews** [comment]
Sure, but my main goal is to make these two specific business views look "good".
