### ISSUE TITLE
Subscribe to event emails doesn't work.

### ISSUE THREAD

**Issue by tmathews** [monstercat/deon#136]
What happened:

When logged in to your account on the website, if you input your location and click ‘subscribe’ on the events page, the button doesn't work.

What was expected:

The button would subscribe me to emails.

**Comment by Vindexus** [comment]
I'm guessing this was because the google places thing was broken. Do you know who sent this in?

**Comment by tmathews** [comment]
Sean did.

**Comment by tmathews** [comment]
Fixed.
