### ISSUE TITLE
Blog twitter social button is uncentered

### ISSUE THREAD

**Issue by btkostner** [monstercat/deon#140]
The twitter social button on the [blog](https://www.monstercat.com/blog/posts/the-monstercat-mailbox/) is uncentered.

![screenshot from 2017-01-20 02 39 35](https://cloud.githubusercontent.com/assets/3385679/22144153/f98e79b4-deb9-11e6-972d-389b5288c7fe.png)

**Comment by tmathews** [comment]
The code for the blog is not contained in this project. The a new blog section is being actively worked on. Thank you for the report.
