### ISSUE TITLE
Blog header creates horizontal scrolling

### ISSUE THREAD

**Issue by btkostner** [monstercat/deon#141]
The `header.header` scale transition on the blog is creating a horizontal scroll bar. If it was my choice, I would remove the scale completely or move it to only scale the background image.

![screenshot from 2017-01-20 02 40 39](https://cloud.githubusercontent.com/assets/3385679/22144227/3a7fd9e0-deba-11e6-91f3-d1b7b0d33f5c.png)

**Comment by tmathews** [comment]
The code for the blog is not contained in this project. The a new blog section is being actively worked on. Thank you for the report.
