### ISSUE TITLE
Playing from playlist doesn't work correctly

### ISSUE THREAD

**Issue by tmathews** [monstercat/deon#162]
**What happened:**

if I try to play track n, it plays track n+1 (https://www.monstercat.com/playlist/589d071cb162ce110bacda11)

**What was expected:**

clicking to play track n should play track n

**Details:**

there was a Gold-exclusive track in slot 1
https://cl.ly/1z2e2S3O2709

**Comment by Vindexus** [comment]
I was pretty sure I fixed this and I'm not able to reproduce it so I'm going to mark it closed.
