### ISSUE TITLE
Playlist row is squished

### ISSUE THREAD

**Issue by tmathews** [monstercat/deon#170]
<img width="1409" alt="screen shot 2017-02-17 at 3 00 31 pm" src="https://cloud.githubusercontent.com/assets/522209/23086477/ea00d982-f521-11e6-885a-e8db16726c9a.png">

Change the input box to be a more appropriate size. Ensure rows are 1 line like the catalog view.

**Comment by juanferreras** [comment]
Fixed in #172 PR
