### ISSUE TITLE
Use the Media Session API

### ISSUE THREAD

**Issue by mistermantas** [monstercat/deon#196]
Introduced in Chrome 57, it adds skipping, scrubbing, pausing, artwork, metadata, and other controls that are present only from native apps.

**Comment by mistermantas** [comment]
@tmathews @Vindexus Well, what’s the status on this?

**Comment by jb55** [comment]
Very cool! Our schedule is a bit busy right now to implement this... but it would be an awesome feature if someone wants to open a pull request. The place to start would be [src/js/player.js](/monstercat/deon/blob/master/src/js/player.js)

**Comment by mistermantas** [comment]
@jb55 Ah, I can make a PR so long as I know what I need to look for. If you’re the developer, can you tell me where I can add the function?

**Comment by mistermantas** [comment]
Actually, I think I found it. Is it:

```js
  function onStateChange(e) {
    this.dispatchEvent(createEvent('statechange', {detail: { player: this }}))
  }
```

…this?

**Comment by mistermantas** [comment]
With #318 closed, I can finally close this issue as well!

YAY!
