### ISSUE TITLE
Settings should go below or beside my info panel.

### ISSUE THREAD

**Issue by tmathews** [monstercat/deon#225]

**Comment by Foxtrek64** [comment]
Something like this?

![image](https://user-images.githubusercontent.com/7003081/28815656-ade7a3fa-7667-11e7-8bb6-be6e2f51a53c.png)

**Comment by tmathews** [comment]
Yes.

**Comment by Foxtrek64** [comment]
I'll fork Deon this weekend and take care of this as well as #223. If someone beats me to it, great, but this is more involved than just cut and paste. I'll see what I can do.

**Comment by tmathews** [comment]
Thanks @Foxtrek64

**Comment by tmathews** [comment]
This seems to be live.
