### ISSUE TITLE
Appears on is empty.

### ISSUE THREAD

**Issue by tmathews** [monstercat/deon#226]
<img width="1405" alt="screen shot 2017-04-10 at 2 32 58 pm" src="https://cloud.githubusercontent.com/assets/522209/24883625/a1a7dfb2-1dfa-11e7-973f-6e7cf038b4ed.png">

**Comment by Foxtrek64** [comment]
Where is this "Appears On" box normally? I've either not seen it or seen it and not taken note of it.

**Comment by tmathews** [comment]
Fixed.
