### ISSUE TITLE
No html or Java files run 

### ISSUE THREAD

**Issue by JordanFisherYT** [monstercat/deon#246]
All the files are broken in this? When was the last time it was updated

**Comment by tmathews** [comment]
Please provide a detailed report on where you are having trouble.

**Comment by JordanFisher2000** [comment]
@tmathews I tried to load the html files and it does not load. My friend even tried to load them and he said its broken. How exactly can I load this?

**Comment by tmathews** [comment]
You need to build the project first, then you can access the index.html from the built folder. You can also run the other scripts to simulate a running server environment. From what you have described, it sounds like you are dragging and dropping source html files into the browser.

**Comment by JordanFisher2000** [comment]
@tmathews ok. And what software do I use. Im new to all this btw

**Comment by tmathews** [comment]
It currently uses the bash environment to run commands. You'll need NodeJS installed as well. I would advise you learn the required environment setup before trying to build.

**Comment by JordanFisher2000** [comment]
@tmathews  ok thanks. i will let my friend know about what you said because he can code

**Comment by tmathews** [comment]
np
