### ISSUE TITLE
Couldn't Build Index

### ISSUE THREAD

**Issue by mayed505** [monstercat/deon#248]
I tried building the index.html
whenever i run "npm install" i get this error
https://gyazo.com/856c81f4e778b24628dd9dae09abc853
im new to build npm and nodejs but i used nodejs before
helping me build index.html would be nice to have

**Comment by tmathews** [comment]
Do you have git installed? Looks like the log is indicating that the git command failed.

**Comment by mayed505** [comment]
yes git bash whatever its called

**Comment by mayed505** [comment]
even running on c9.io same error
https://gyazo.com/fd090a2fc1e3418a53ddc57fe951d534

**Comment by btkostner** [comment]
That seems to be a permission error. Try doing `chmod +x ./scripts/serve`. You might need to run it with `sudo chmod +x ./scripts/serve`.

**Comment by Foxtrek64** [comment]
@mayed505 How are you wanting to "contribute" and "see how this works?" You can always see a live version of the site at [monstercat.com](https://www.monstercat.com) and the best way to contribute is to find open issues and try to fix them.

That being said, I've run into similar issues on other projects (based on your error log). Make sure Node and NPM are updated to the latest versions.

After this, run `sudo su` and type your administrative password, then run the build process again. This will ensure that everything is run as the super user and *should* take care of any access denied issues you may be experiencing.

**Comment by tmathews** [comment]
Closing this as it is unrelated to the project itself.
