### ISSUE TITLE
Error [Cast to ObjectId failed for value \"\" at path \"_id\] while trying to download a playlist

### ISSUE THREAD

**Issue by sergiocastell** [monstercat/deon#25]
I tried to download a playlist with some of my favourite songs from Deon, and it thrown me this error message: 
`{"message":"Cast to ObjectId failed for value \"\" at path \"_id\"","name":"CastError","kind":"ObjectId","value":"","path":"_id","error":"Cast to ObjectId failed for value \"\" at path \"_id\""}`
The type of download was FLAC, and there are both new and pretty old songs, if that matters. [This is the playlist itself](https://www.monstercat.com/playlist/57ff674a54c428a56452855f).

**Comment by tmathews** [comment]
Hey, thanks for the report. We will look into it.

**Comment by sergiocastell** [comment]
Hey @Vindexus, any news on this?

**Comment by Vindexus** [comment]
Honestly this slipped through my radar, I'll take a look today. Definitely seems possible some old stuff in your playlist has a blank _id for either the song or the release.

**Comment by tmathews** [comment]
@lostlevels has confirmed the missing ids in the playlist.

**Comment by lostlevels** [comment]
Thanks for the heads up @sergiocastell 
It should be fixed now.

**Comment by sergiocastell** [comment]
Thanks guys! Have a nice day.
