### ISSUE TITLE
Change Add to Playlist from dropdown to modal

### ISSUE THREAD

**Issue by Vindexus** [monstercat/deon#319]
This issue is part of our [Bounty Hunter Program here](https://www.monstercat.com/dev/bounties).

## Reward
$40 USD

## Requirements
 - Replace the `Add to Playlist` with an icon button that opens a modal.
 - Use the `fa-plus` icon for the button. Use same classes as the Copycredit and Download buttons.
 - The modal should show you your playlists. Each one should be a button that will add the track to that playlist.
 - After clicking a playlist the button should change to have a spinner in it while the request is sent to the server.
 -You should also be able to add the track to a **new playlist**. Have a separate form above the list of playlists with a "Playlist Name" text field and "Add to New Playlist" button.
 - Name is a required field.
 - Submitting the form should create a new playlist and add the track to it
 - Any server errors should show in the modal
 - On success the modal should close and a `toasty` should pop up with a success message

## Guidance
Do a global search for these useful items:
`addToPlaylist`  
`template-name="select-playlist"`
`canPlaylist`
`openModal`

Also see `templates/modals.html` and `src/playlist.js` files.

**Comment by tmathews** [comment]
Via #325
