### ISSUE TITLE
Connect API Filter not working

### ISSUE THREAD

**Issue by Xerus2000** [monstercat/deon#329]
See for example here: https://connect.monstercat.com/api/catalog/track?fields=type,title,artists,renderedArtists&filter=title,worth%20the%20lie&limit=3

The filter parameter does absolutely nothing, despite being listed on the official API doc [here](https://www.monstercat.com/dev/api/connect)

**Comment by Vindexus** [comment]
Good catch. The field is actually `filters`, with an S. I've updated the docs. Also keep in mind it's case sensitive.

There's also a new route at /api/catalog/browse you might want to look into.

**Comment by Xerus2000** [comment]
Ouh looks nice! Why can't I filter browse though? Is it yet to be implemented?

**Comment by Vindexus** [comment]
You can, you just have to use the "search" field.
