### ISSUE TITLE
Submit demo button doesn't work

### ISSUE THREAD

**Issue by mistermantas** [monstercat/deon#340]
And it hasn't for a while. I don't know if this is intentional or if Monstercat really does not want any more demos. Witnessed on this page:

https://www.monstercat.com/contact

**Comment by tmathews** [comment]
@Vindexus didn't we revert it back to tracksubmit?

**Comment by tmathews** [comment]
I believe this is the problem: https://github.com/monstercat/deon/commit/ed630628c8949bdc0ebd0afc001538327b533966#diff-4a38c195ebf3acc3ecd9234dc52f52daR216

**Comment by tmathews** [comment]
Fixed.
