### ISSUE TITLE
Careers link broken

### ISSUE THREAD

**Issue by mistermantas** [monstercat/deon#341]
Should add a slash for the redirect to work.

404 on: https://www.monstercat.com/careers

good: https://www.monstercat.com/careers/

**Comment by tmathews** [comment]
No slash appears to work. Please report how you are accessing this.

**Comment by mistermantas** [comment]
Accessing from my phone. Chrome Dev 66, on WiFi. Basically it's a modern browser and I see a 404. It probably works on desktop.

**Comment by mistermantas** [comment]
![](https://i.imgur.com/OwvY1Hu.png)

**Comment by tmathews** [comment]
Oh, it's related to this: #340
Closing as duplicate.
