### ISSUE TITLE
Playing a song on mobile can be annoyingly hard

### ISSUE THREAD

**Issue by Xerus2000** [monstercat/deon#362]
While using the Monstercat website on my phone, whenever I clicked on the play button, the social media of the artist popped up. I had to carefully tap on the left or right edge of the button to actually play something. I guess there is some hitbox overlapping where it shouldn't be.

![screenie](https://user-images.githubusercontent.com/13354331/37929728-0b0a3cfc-3141-11e8-8604-f6a7a764d67c.jpeg)

**Comment by fraserdarwent** [comment]
Fixed by https://github.com/monstercat/deon/commit/a679b7dce94176b86d6cc12b920243a2be9bfd4e
