### ISSUE TITLE
Playing from playlist shows playing from anywhere.

### ISSUE THREAD

**Issue by GiovanniMCMXCIX** [monstercat/deon#37]
When you're playing a track from another playlist, album search it shows that is playing everywhere.

![image](https://cloud.githubusercontent.com/assets/10764652/19814867/d8c1ffb0-9d48-11e6-8166-a50615646193.png)

![image](https://cloud.githubusercontent.com/assets/10764652/19814694/0634985a-9d48-11e6-9022-3fefbdf198c6.png)

![image](https://cloud.githubusercontent.com/assets/10764652/19814811/8e8632ae-9d48-11e6-87ef-f72dfae4d9d5.png)

**Comment by tmathews** [comment]
Thanks

**Comment by Vindexus** [comment]
I'm not convinced this should be changed. The song on the page _is_ playing, even if not from the list you're looking at. What's the expected behaviour if it shows a play icon and you click it for a song that's already playing?

**Comment by tmathews** [comment]
I agree.
