### ISSUE TITLE
Issues with player controls state

### ISSUE THREAD

**Issue by tmathews** [monstercat/deon#39]
> I can't explain these ones so I recorded them:
> https://www.dropbox.com/s/hvg9ev06h6smawt/2016-10-28%2020-20-53.flv?dl=0
> https://www.dropbox.com/s/hvg9ev06h6smawt/2016-10-28%2020-20-53.flv?dl=0
> sorry if the videos are kinda garbage
- @GiovanniMCMXCIX

**Comment by Vindexus** [comment]
When you go to the playlist are you clicking that track's play icon and it isn't pausing it? Is that the issue here? There's definitely some quirks to playing a song on one page then navigating to another page it's on. This helps with them a little bit: https://github.com/monstercat/deon/pull/193

**Comment by tmathews** [comment]
Closing for now. Will reopen if arises again.
