### ISSUE TITLE
Playlist metadata issues

### ISSUE THREAD

**Issue by tmathews** [monstercat/deon#4]
Add same song to your playlist twice and the meta data fails to show for that song on both rows.
Sometimes meta data for releases doesn't show either.

**Comment by lostlevels** [comment]
This is on the playlists page right? Does this still happen?

**Comment by tmathews** [comment]
Yes. Yes.

**Comment by tmathews** [comment]
Put on back burner until we find an example.

**Comment by tmathews** [comment]
Example where release information is not showing up.
https://www.monstercat.com/playlist/57ff674a54c428a56452855f

**Comment by lostlevels** [comment]
This is a backend issue where it's returning deleted albums with a track. The playlist in question has already been created with a missing release id so would have to manually edit that one. Will create a backend fix.

**Comment by tmathews** [comment]
Cool
