### ISSUE TITLE
Background is missing

### ISSUE THREAD

**Issue by GiovanniMCMXCIX** [monstercat/deon#40]
> Failed to load resource: https://www.monstercat.com/img/bgon.jpg the server responded with a status of 404 ()

**Comment by tmathews** [comment]
Could you give us more details on where you are receiving this issue? The current issues does not provide enough of a description for us to work on it.

**Comment by GiovanniMCMXCIX** [comment]
When I turn `I Like Backgrounds` it gives a black background and it doesn't load the image
![image](https://cloud.githubusercontent.com/assets/10764652/19823375/ea69d8c8-9d70-11e6-9f5b-f88562517f5d.png)

**Comment by tmathews** [comment]
Thanks.

**Comment by tmathews** [comment]
@juanferreras can you get us a cool image to use?
