### ISSUE TITLE
MCEP104's track order is messed + missing a track

### ISSUE THREAD

**Issue by GiovanniMCMXCIX** [monstercat/deon#42]
After 5 AM *my hour when usualy releases come out or when they get out of prelease* MCEP104 started to act strage by the release not downloading saying that the resource is missing and still showing as a preorder then 2 hours is gone from the [release page](https://www.monstercat.com/release/MCEP104)

![image](https://cloud.githubusercontent.com/assets/10764652/19845805/05044262-9f43-11e6-93da-b41197f5115b.png)

 and from the [api](https://connect.monstercat.com/api/catalog/release/MCEP104)

![image](https://cloud.githubusercontent.com/assets/10764652/19845850/6e5a5e72-9f43-11e6-9ee2-ada623459d95.png)

**Comment by GiovanniMCMXCIX** [comment]
sorry for not updating, anyway the release page was back after 3 hours of so but still the order of the tracks is messed up and the radio edit of The Pink Killing Floor is missing

**Comment by tmathews** [comment]
Thanks for the report. Please make sure to separate issues into their own tickets.

**Comment by tmathews** [comment]
Fixed.
