### ISSUE TITLE
Give bots more song info

### ISSUE THREAD

**Issue by hugopilot** [monstercat/deon#531]
When I post links on discord and WhatsApp, the website returns the mcat slogan. Would it be a good idea to return some song info or thumbnail?

Example:
![Dis is an iMAgE](https://user-images.githubusercontent.com/10338882/56497732-21527180-64ff-11e9-8f63-416687b386ce.png)

**Comment by linuxct** [comment]
This issue has already been addressed, I can see OG parameters in the HTML head and the album art and song title part of the link. Tagging @tmathews
