### ISSUE TITLE
Connect stats.json response contains a badly formatted output for "twitchmonstercat" 

### ISSUE THREAD

**Issue by linuxct** [monstercat/deon#565]
![image](https://user-images.githubusercontent.com/3966313/62188060-8c67db80-b36b-11e9-94ae-379ee5197323.png)

For "twitchmonstercat" on Connect's stats.json response, it's formatted without a value and a name, leaving just a number. 

Is it correct like that? If it is, I'm willing to opening a PR to also parse sole numbers as proper input to feed the page's counters.

Current stats response: [stats.json](https://github.com/monstercat/deon/files/3450131/stats.json.txt)

**Comment by tmathews** [comment]
It's probably wrong, but also the website could be reading it differently for just that one value (which would be bad IMO).

**Comment by tmathews** [comment]
Fixed.
