### ISSUE TITLE
Prefix declare attributes with data-/use HTML data

### ISSUE THREAD

**Issue by binki** [monstercat/deon#62]
See discussion in #60.

It is harder to use `<form/>` elements because declare uses `action` attribute as special meaning. For example, trying to place a “real” form (or one that can be upgradeable to AJAX) with an `action` attribute causes declare to do things whenever you click on any elements that are descendants of the `<form/>`.

HTML has special support for attaching arbitrary data to elements using the `data-` attribute prefix and providing the [`HTMLElement.dataset`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dataset) API for this purpose.

Thus, I propose that declare namespace its attributes accordingly.

**Comment by tmathews** [comment]
I don't think we have to use the `data-` prefix. Just another word that does not conflict with the specification. Suggestions welcome.

**Comment by tmathews** [comment]
Not going to work on due to time and resources.
