### ISSUE TITLE
Make forms more declarative by using HTML form elements and attributes

### ISSUE THREAD

**Issue by binki** [monstercat/deon#63]
With how declare is now, `<forms/>` are actually rather non-declarative. It would be cool if they could use the traditional HTML elements like `action` and `method` and have declare extract this information from those HTML-provided attributes instead of this all living in JavaScript. They can still be just as AJAXy as they are now, but might not need as much dedicated JavaScript as they currently use.

See discussion in #60. Also, I think #62 might have to be completed before this issue can be pursued.

**Comment by tmathews** [comment]
Agreed.

**Comment by tmathews** [comment]
I don't think we will be updating this version of declare any time due to the amount of work it would take to ensure a proper transition.

**Comment by tmathews** [comment]
@binki see https://github.com/monstercat/declare
