### ISSUE TITLE
Separate CSS files.

### ISSUE THREAD

**Issue by tmathews** [monstercat/deon#71]
The main CSS file is getting too big. It should be reserved for site styles. Let us move specific page styles into their own since we are using HTTP2.

**Comment by juanferreras** [comment]
The idea is just splitting the files for organizational purposes and still link *all of them* on the website's `<head>`? Or to try to build something that updates the CSS on page change accordingly (not sure how I would tackle something like that, but maybe it's possible).

**Comment by tmathews** [comment]
Just separate the files into small chunks and have all of them in the head tag like we do for JavaScript.

**Comment by juanferreras** [comment]
addressed in PR #134
