### ISSUE TITLE
You can manage to get the stream hash of preorder/gold early access tracks

### ISSUE THREAD

**Issue by GiovanniMCMXCIX** [monstercat/deon#92]
You can the stream hash from https://connect.monstercat.com/api/catalog/track/ without being logged in

Example:
1. Nerds By Nature
* Speed of Light: https://connect.monstercat.com/api/catalog/track/582256fc591226e4046b2ede
`"streamHash":"981fd1a0da58f58c2f1ddadc4fda57ce6e1b7e19"`
* Talk About It https://connect.monstercat.com/api/catalog/track/5822570a591226e4046b2ee3
`"streamHash":"bafd193165d1125f1f1963897735433d2b984007"`
* Go Berserk https://connect.monstercat.com/api/catalog/track/58225721591226e4046b2ee8
`"streamHash":"bb890470aea5e6c73262fd201a20ffe5e3dde480"`
2. Chipland https://connect.monstercat.com/api/catalog/track/583373124031b36f516ed3f9
`"streamHash":"e01c2a2698f061b3d4669dd43e4e061ab55305c2"`

**Comment by Vindexus** [comment]
Thanks for the heads up.

**Comment by Vindexus** [comment]
Just double checked this and it's working as intended. You don't need to be logged in to get the streamHash for released tracks. You only need to be logged in as Gold to get streamHash for tracks that are in early access, otherwise the field is set to null.
