### ISSUE TITLE
Roster years take too much space on small screens 

### ISSUE THREAD

**Issue by juanferreras** [monstercat/deon#97]
We should look into a better way to handle this for small devices as filtering takes up half a mobile screen.

**Comment by juanferreras** [comment]
What about having an accordion? So it shows the `FEATURED` button on all resolutions, but you need to tap on `SHOW YEARS` on mobile devices to display all the years to be able to tap on the one you want. You may also tap on `HIDE YEARS` after to hide them back so they stop cluttering on your screen.

**Comment by tmathews** [comment]
What about a hidden select field in mobile so that when you tap on hidden the native selector pops up and shows the options?
